- crawler-user-agents.json
Details of crawler on their website http://www.screamingfrog.co.uk/seo-spider/
> Adding Screaming Frog SEO Spider

- crawler-user-agents.json
Sorry, there are more than five additions at once.  I can split it up into two commits if necessary.
> added 7 more bots found in logs

- crawler-user-agents.json
https://support.google.com/webmasters/answer/1061943?hl=en
> Update Google crawlers

- README.md
- crawler-user-agents.json
I noticed there's a decent bit of trailing whitespace in the JSON file especially. I figured I might as well clean it up.
> Remove trailing whitespace

- crawler-user-agents.json
There are two bot entries that are duplicated after the recent pr merges and two entries that are missing.
> Removed duplicates and re-added missing bots

- crawler-user-agents.json
Found the following user-agent in my logs: `Mozilla/5.0 (compatible;contxbot/1.0)`
> Added contxbot user agent

- crawler-user-agents.json
Found this user agent `Pinterest/0.2 (+http://www.pinterest.com/bot.html)` in my logs.
> Added Pinterest bot

- crawler-user-agents.json
> Add BingPreview bot

- crawler-user-agents.json
I noticed this bot in my logs today.
> Add Vebidoobot

- crawler-user-agents.json
https://help.yahoo.com/kb/mail/yahoo-link-preview-SLN23615.html
> Add Yahoo Link Preview user agent

- crawler-user-agents.json
Noticed this Bot today in the log of one of the new sites I'm maintaining
> Add MetaJobBot

- crawler-user-agents.json
> Add DomainStatsBot

- crawler-user-agents.json
These German Sites I start to manage are an endless resource of new Bots it seems.
> Add mindUpBot

- crawler-user-agents.json
This way more patterns are validated. I got most of the new examples from https://github.com/JayBizzle/Crawler-Detect/blob/master/tests/crawlers.txt
> Add more instances of most patterns

- crawler-user-agents.json
- test_validation.py
- validate.py
This pulls out just the case sensitivity changes in #62
> Make validation case sensitive

- validate.py
I'm a Python guy, so I made `validate.py` more Pythonic. I also fixed some case sensitivity issues, because many of these patterns will match too much if you're using them insensitively—`pinterest` being a prime example.
> Clean up validate.py

- crawler-user-agents.json
>  Fixed #70 - added missing capitalisation

- crawler-user-agents.json
- test_validation.py
- validate.py
(plus a correction to a mistake I made in the previous PR)
This should be my last one for a while hopefully - this is everything that was remaining in my logs.
Thanks
> Another batch of user-agents

- crawler-user-agents.json
Seems that this removes whitespaces too.
> Add Botify

- crawler-user-agents.json
Submitting some bots from our January logs
> Add 007ac9

- crawler-user-agents.json
Submitting some bots from our January logs
> Add BehloolBot

- README.md
- package.json
Updated the documentation to add install instructions and usage in JavaScript.
Also added the `main` field to the `package.json` to make the package `require()`able in Node.js.
> Doc: update usage

- crawler-user-agents.json
Adds the follow bots into one PR:
- BLP_bbot, closes #93
- BomboraBot, closes #100 
- Buck, closes #97 
- Campanybook-Crawler, closes #96 
- Genieo, closes #101 
- Magpie-Crawler, closes #102 
- MeltwaterNews, closes #95 
- Moreover, closes #94 
- Newspaper, closes #98 
- ScoutJet, closes #91 
- Sentry, closes #103 
- StorygizeBot, closes #99 
- UptimeRobot, closes #92
> Add additional bots/crawlers

- crawler-user-agents.json
Add user-agent for version 1.4.8 of MJ12bot
> Update MJ12bot - version 1.4.8

- crawler-user-agents.json
> Add OutclicksBot

- crawler-user-agents.json
https://www.distilnetworks.com/bot-directory/bot/google-web-preview/
https://www.webmasterworld.com/search_engine_spiders/4223018.htm
https://stackoverflow.com/questions/45826598/useragent-google-web-preview-bot-or-not
> Add Google Web Preview

- crawler-user-agents.json
I had some old crawler records files. I wanna replaced it with yours. Add some bot crawler we had while missing here
@monperrus rfr
> adding more bot crawlers

- crawler-user-agents.json
VK is a very well known social media like Facebook in east Europe countries such as Russia and Ukraine.
> Add VK Share crawler bot

- crawler-user-agents.json
retry for https://github.com/monperrus/crawler-user-agents/pull/111
I've removed commits without example.
> Fix too simple patterns

- crawler-user-agents.json
Diffbot, Feedspotbot, Miniflux, ZuperlistBot, Hatena, DareBoost, BLEXBot
> Add multiple bots

- crawler-user-agents.json
This PR adds `google-xrawler`, a bot used by Google for fetching Google Shopping feeds.
> Add google-xrawler

- crawler-user-agents.json
https://github.com/axios/axios
> Add `axios`

- crawler-user-agents.json
https://aws.amazon.com/cloudfront/
> Add `Amazon CloudFront`

- crawler-user-agents.json
@monperrus rfr
Adding a crawler (Seekorit Crawler) I am keep seeing from our logs.
> Adding Seekport Crawler

- crawler-user-agents.json
@monperrus rfr
sorry for previous pr, didn't pay much attention to the RSS feeders.
> Add Moodlebot, jpg-newsbot, VelenPublicWebCrawler bots

- README.md
I wrapped this library up in a small Clojure library called [crawlers](https://github.com/Olical/crawlers). I thought I'd format the related work as lists and add it here since it might come in handy for others in the future.
> Turn related work into lists and add my wrapper

- crawler-user-agents.json
See title and commit message. A yacybot was missing.
> Another yacybot added

- crawler-user-agents.json
Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1; +http://ahrefs.com/robot/)
First commit - not sure if there's any rules.  I hope note
> AhrefsSiteAudit/6.1 (#1)

- crawler-user-agents.json
https://developers.google.com/speed/pagespeed/insights
Supersedes #170
> Add Chrome-Lighthouse (Google Page Speed Insights)

- crawler-user-agents.json
+ change the URL since the old one is a 301 to a 301 to the new link
> Add an additional instance

- crawler-user-agents.json
This reverts commit dba21792bb4fc9e2dc92dfa679917af9701e8702.
> Revert "add googlebot instance (#199)"

- README.md
[isbot](https://github.com/gorangajic/isbot/blob/master/scripts/download-crawlers-json.sh) now covers the file list in this repository! 🎉 (https://raw.githubusercontent.com/monperrus/crawler-user-agents/master/crawler-user-agents.json) And planning to continue to do so via automated jobs.
> isbot now covers this repo!

- crawler-user-agents.json
User Agent - Mozilla/5.0 (X11; Datanyze; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
> Datanyze (https://www.datanyze.com/dnyzbot/)

- crawler-user-agents.json
These are real-world bots that we see daily and we have added manually to account for the fact that they are not present in this repo. I hope this is helpful for others as well.
> Add more users agents of bots found in the wild

- README.md
> doc: fix link to the isbot repo

- crawler-user-agents.json
Actualize all info for Yandex bots by current (2020/11/30) information from https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.xml#robot-in-logs
> Add missing users agents of Yandex bots

- crawler-user-agents.json
These user agents make up about 1% of the traffic received by our server. Would it be possible to get them added to the list?
Thanks!
> Add PHP-Curl-Class

- crawler-user-agents.json
> add virustotal

- crawler-user-agents.json
New version 7.0 is not yet in the instances. Thx.
> Add instance for AhrefsBot

- crawler-user-agents.json
Adding minicrawler (testomatobot) to the patterns.
[Testomato](https://www.testomato.com/) is website monitoring service using https://github.com/testomato/minicrawler for crawling websites and uptime monitoring.
> Add minicrawler

- crawler-user-agents.json
Closes https://github.com/monperrus/crawler-user-agents/issues/291
> Add `FreshpingBot`

- crawler-user-agents.json
This is probably a replacement for `Seekport Crawler`, but I'm not 100% sure on this.
> Add `SeekportBot`

- README.md
PHP usage example has some weird `ì` character which I just updated to `i`... :)
> doc: fix php usage example

- crawler-user-agents.json
1. Semrush instance - This instance wasn't detected for some reason - could it be the regex is
broken, or instances are relied on somehow?
2. Add another observed instance for bingbot, which again wasn't detected
> Fix bingbot sermrush

- crawler-user-agents.json
This is very needed for anyone using Better Uptime Bot Mozilla on Heroku
> Added Better Uptime Bot

- crawler-user-agents.json
> Add Google-Read-Aloud

- crawler-user-agents.json
Threw error when I tried to parse URL in JS.
> Fix an invalid pattern

- crawler-user-agents.json
Add
- YandexRenderResourcesBot
- LightspeedSystemsCrawler
- ev-crawler
- BitSightBot
- woorankreview
- Google-Safety
> Add YandexRenderResourcesBot, LightspeedSystemsCrawler,  ev-crawler, BitSightBot, woorankreview

- crawler-user-agents.json
> add linespider

- crawler-user-agents.json
> Add GeedoBot

- crawler-user-agents.json
- validate.py
fix date problem by @starius in https://github.com/monperrus/crawler-user-agents/pull/348
> add date validation

- crawler-user-agents.json
Found in the logs of [PhoneBlock](https://phoneblock.net).
> Add ClaudeBot

- crawler-user-agents.json
Adding the Monsidobot user agent
> Adding Monsidobot and removing whitespace

- __init__.py
- crawler-user-agents.json
- added GroupMe bot pattern
- fefactor + fix \_\_init\_\_
> patterns json: add support for GroupMe bot

- crawler-user-agents.json
Adds new instance for Google Lighthouse bot.
> Add Chrome-Lighthouse instance

- crawler-user-agents.json
While digging into each bot, I discovered some inconsistencies in the metadata. This updates/adds some URLs and instances.
> chore: Update some links & instances

- crawler-user-agents.json
> Add OpenAI Search Bot

- crawler-user-agents.json
Happy to split these into three separate commits if preferred.
> Add facebookcatalog, meta-externalagent, and meta-externalfetcher

- crawler-user-agents.json
AcademicBotRTU (https://academicbot.rtu.lv; mailto:caps@rtu.lv)
> Update crawler-user-agents.json with AcademicBotRTU 

- crawler-user-agents.json
The User-Agents for Uptime Kuma.
> Added Uptime Kuma User-Agent

- crawler-user-agents.json
I've created a new PR for this crawler to hopefully avoid any merge conflicts + get rid of the force push I did in the first version of this PR.
> User-Agent for Lemmy crawler

- crawler-user-agents.json
User-Agent for the SummalyBot.
> Added SummalyBot User-Agent

- crawler-user-agents.json
Added `MicrosoftPreview`, another [Bing crawler User-Agent](https://www.bing.com/webmasters/help/which-crawlers-does-bing-use-8c184ec0)
> Added MicrosoftPreview

- crawler-user-agents.json
Add missing oncrawl instances into JSON file.
> feat: add oncrawl instances

- crawler-user-agents.json
Adding a rule for the sitebob crawler https://sitebulb.com/
> feat: add sitebulb bot

- crawler-user-agents.json
Documentation [here](https://hitchhikers.yext.com/modules/kg140-yext-site-crawler/01-create-a-crawler/).
> add Yext crawler/scraper bot

- crawler-user-agents.json
Documentation [here](https://developers.facebook.com/docs/sharing/webmasters/web-crawlers).
> Add meta-externalads user agent
