crawler-user-agents.json
I got those bots in our records:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)
I haven't put instances for Applebot because it's very variable.
Mozilla/5.0 (TweetmemeBot/4.0; +http://datasift.com/bot.html) Gecko/20100101 Firefox/31.0
=> adds Applebot and TweetmemeBot

crawler-user-agents.json
It's used by WhatsApp URL preview crawler in iOS & the desktop web app (https://web.whatsapp.com/)
Example User Agent:
WhatsApp/2.16.16/i
=> WhatsApp preview crawler native iOS & Webapp

crawler-user-agents.json
According to https://udger.com/resources/ua-list/bot-detail?bot=voyager,
this bot has been inactive for quite some time. Kosmix was acquired by
walmartlabs.
See issue #35
=> Remove Voyager bot

LICENSE, package.json
To be clear: this is not supposed to be published to npm or other registries, as the author has previously mentioned to not be willing to publish and maintain a package in the registry. [[1]](https://github.com/monperrus/crawler-user-agents/issues/14#issuecomment-175269246)
Instead, by simply adding a `package.json` file to the repository, it will allow consumers to install the package directly from GitHub through yarn/npm. For instance:
```
yarn add "https://github.com/monperrus/crawler-user-agents.git#d5ee77dad02fed5d391bb3295355932a9f154071"
npm install "https://github.com/monperrus/crawler-user-agents.git#d5ee77dad02fed5d391bb3295355932a9f154071"
```
This will not require any future changes from the maintainers, the `package.json` is marked with the `private` flag to prevent …
=> Add package.json to allow installing directly from GitHub

.gitignore, .travis.yml, test_validation.py
Fixes #63
There are no tests for case sensitivity, but those should be added after the validation code is made case sensitive.
=> Add tests for validate.py

crawler-user-agents.json
NB: This contains some entries that you may or may not wish to add!
In particular:
- "TelegramBot" and "DiscordBot" are not conventional spiders but clearly aren't "real" site visitors and are instead used (I believe) to obtain OpenGraph data for link previews
- "InfoPath.2" isn't a specific bot referrer but allows spotting automated requests from scripts
Some entries have missing "url" fields because the requests they were sourced from did not contain a URL in the referrer info.
Thanks
=> Add 30 new bot patterns

crawler-user-agents.json, test_validation.py, validate.py
I noticed that I was running into problems with the latest crawler-user-agents and realised that there were some duplicates that weren't being caught by validate.py as the patterns had different case (rather than having a single pattern matching both capitalisations).
I've updated crawler-user-agents.json to ensure that we're still passing the validation with this slightly more stringent check.
I am *not* a python person, so definitely improve my validate.py addition if there is a better way of doing this
=> Validate.py: case insensitive duplicate check

README.md
Pull request to fix #76 
This adds links to language specific front-ends to crawler-user-agents, and to other repositories that are alternatives to crawler-user-agents.
Thanks
=> Added links to other repos in README (#76)

crawler-user-agents.json
This PR adds `Zabbix`, a bot used by a tool called [Zabbix](https://www.zabbix.com/), the bot checks for a HTTP response as part of monitoring the uptime of services.
=> Add Zabbix

crawler-user-agents.json
This PR adds `TangibleeBot`, a bot used by a service called Tangiblee, the bot scans web pages for data that it then uses to produce a product comparison tool.
You can find out more about the service here: http://tangiblee.com
=> Add TangibleeBot

crawler-user-agents.json
This PR adds `Datafeedwatch`, a bot used by a tool called DataFeedWatch that allows you to monitor product listings.
=> Add Datafeedwatch

crawler-user-agents.json
I'm not sure, because Jersey is wrapper around HttpUrlConnection Java-library,
which is also in the User-Agent header, as I understood.
=> Add Jersey

crawler-user-agents.json
Adds Outbrain and the W3C validator bots listed [here](https://validator.w3.org/services) other than NING which is [already present](https://github.com/monperrus/crawler-user-agents/blob/master/crawler-user-agents.json#L2518-L2521).
=> Add outbrain and w3c bots

crawler-user-agents.json
I could not find an official URL, but here are three links I found on the internet (there are more, but I picked three arbitrarily):
https://www.distilnetworks.com/bot-directory/bot/google-favicon/
https://www.seroundtable.com/google-favicon-crawler-26522.html
https://twitter.com/VorticonCmdr/status/1051851131499020288
I've been seeing this User-Agent in my webserver logs.
=> Add Google Favicon bot

README.md, package.json
Hi Martin, thanks for your work. It is extremely useful repo, but now there are several errors in npm setup.
1. All npm packages can be installed without git-repo url
2. [Npm page](https://www.npmjs.com/package/crawler-user-agents) hasn't link to github repo in the info column
This PR will correct errors after `npm publish`.
=> Added git page to package.json and changed README

crawler-user-agents.json
fix #175 
When the goal is to filter out all types of automated UAs, it will be useful to filter out headless browser UAs as well. While identifying all headless browsers is a different exercise all together, there are some headless browsers like Chrome 74, which identify themselves explicitly via their UA. Hence, such UAs may be included in this list.
=> added UA string and pattern for HeadlessChrome on Linux

crawler-user-agents.json
Agent "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0":
I believe this agent string is used by no legitimate browsers, but Samsung's phone native SMS app that fetches previews with this outdated string. I suppose it's now safe to assume that incoming requests as this can be considered crawlers.
See:
https://developer.samsung.com/forum/thread/sms-link-rich-preview/201/346325?boardName=SDK&startId=zzzzz~
https://stackoverflow.com/questions/48068227/details-on-user-agent-mozilla-5-0-x11-ubuntu-linux-i686-rv24-0-gecko-2010
https://stackoverflow.com/questions/48957233/what-is-the-samsung-link-preview-user-agent
Agent "SimpleScraper" (unrelated to previous, just found it along the way):
https://github.com/ramonkcom/simple-scraper/tree/master/src
=> add simplescraper

crawler-user-agents.json
This entry seemed weird to me as well, so I did a little bit of log-crawling.
I isolated the calls from DuckDuckGo and then grouped by UAs and IPs, and those are the results:
Mozilla/5.0 (compatible; DuckDuckGo-Favicons-Bot/1.0; +http://duckduckgo.com)
1 - 54.208.102.37
201 - 107.21.1.8
Mozilla/5.0 (compatible; DuckDuckBot-Https/1.1; https://duckduckgo.com/duckduckbot)
4 - 52.204.97.54
1 - 50.16.241.117
1 - 50.16.247.234
1 - 50.16.241.113
'Mozilla/5.0 (compatible; DuckDuckBot-Https/1.1; https://duckduckgo.com/duckduckbot)'
126 - 52.204.97.54
2 - 50.16.241.117
1 - 50.16.247.234
The fact that all IPs that use the "weird" UA are in the list available at https://duckduckgo.com/duckduckbot, makes me think this UA is legittimate.
=> Adding instance to duckduckgo

crawler-user-agents.json
We see a large amount of bot traffic with agents ending with 'Bytespider'. One example: "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.5939.1534 Mobile Safari/537.36; Bytespider".
I started to include an instances list, but then realized it presents with literally thousands of different user agent strings.
see:
https://stackoverflow.com/questions/57908900/what-is-the-bytespider-user-agent
https://udger.com/resources/ua-list/bot-detail?bot=ByteDance+crawler
I couldn't find any official web page for this crawler to include in the JSON for this crawler.
=> add Bytespider

crawler-user-agents.json
At the moment only sync Python HTTP clients is defined as bot, in this PR, I add detection of async clients [aiohttp](https://docs.aiohttp.org) and [httpx](https://github.com/encode/httpx).
=> Add async Python HTTP Clients

crawler-user-agents.json
This showed up in some logs for a Google Cloud-hosted site while creating HTTPS certificates. It's used for domain verification under the [RFC 8555](https://tools.ietf.org/html/rfc8555) protocol.
=> Add Google-Certificates-Bridge.

crawler-user-agents.json
https://www.webpagetest.org/. Adds PTST/<version> to the end of the user agent string by default.
=> Add webpagetest.org (PTST)

crawler-user-agents.json
Steam's bot is visiting my server and the corresponding pattern to detect this bot is missing. I'm adding it here.
=> Add Steam bot (SteamChatURLLookup)

crawler-user-agents.json
Use a single regex for all bots (less mantainance burden, faster to use, ...)
Note that this also matches YandexUserproxy, which was not handled before:
Mozilla/5.0 (compatible; YandexUserproxy; robot; +http://yandex.com/bots
=> Merge all yandex bots together

.github/workflows/npm-publish.yml, .travis.yml, package-lock.json, package.json
Add pacote (at v11.1.11) as a proper npm dependency because it was being installed in CI dynamically. It is added as a devDependency because users of the package do not need it so shouldn't be included for them. Accordingly, update CI pipelines to use `npm clean-install`, which will install exactly what is in the lockfile, for more details see: <https://docs.npmjs.com/cli/v10/commands/npm-ci>.
This change hardens the supply chain. Before, even if you trust npm to be immutable and always give you the same code for pacote, it would resolve different versions of transitive dependencies (evidenced by the presence of version ranges in the dependency list for pacote in the newly added lockfile, line 1294 to 1314). Now, both direct and transitive dependencies are pinned, and their checksum can …
=> Add npm dependencies with lockfile

crawler-user-agents.json
Found in the logs of [PhoneBlock](https://phoneblock.net). Users of ChatGPT make the AI look up info from the web.
=> Add ChatGPT-User - another bot from openai.com

crawler-user-agents.json
There are instances that only identify themselves with an upper case letter at the beginning. The original instances currently known also contain the pattern with the upper case letter.
Found in the logs of [PhoneBlock](https://phoneblock.net).
=> Fix pattern of Nutch crawler

.github/workflows/ci-validation.yml, .travis.yml, requirements.txt
NOTE: I'm not very experienced with Python dependency management and pip. My goal here is similar to #351 but for pip.
This adds a `requirements.txt` file to pin Python dependencies, direct and transitive. This was achieved by, in a clean Docker image, first running `pip3 freeze` to get a list of irrelevant packages, then running the existing `pip3 install jsonschema pytest` (from CI) command, and finally running `pip3 freeze` again to get this project's dependencies (by omitting those from the first `pip3 freeze` list).
Both CIs have been updated to use the `requirements.txt` file to install dependencies. Besides improving reproducibility, this also avoids duplication.
The benefit of doing this is that the same versions of Python dependencies will always be used for this project …
=> Add and use `requirements.txt`

crawler-user-agents.json
This combines the Seekport rules. I noticed this as I tried to name all the rules. It seems that Seekport might have changed their user-agent at some point but simplifying the pattern catches both.
=> chore: Combine seekport rules

crawler-user-agents.json
This adds some Vercel bots.
I'm still trying to get an instance of `vercel-screenshot` to include.
=> feat: Add Vercelbot and vercel-screenshot user-agents

.github/workflows/ci-validation.yml, crawler-user-agents.json, format.js
While working on some other PRs, I noticed that VSCode was trying to reformat a lot of this file. This is the format that it really wants to apply.
I think the comma on separate lines was supposed to make adding new entries easier but it was lost at some point. If those should remain, let me know and I can try converting the items that don't adhere to that style; however, I figured following a common editor formatting would make for less churn in future PRs.
=> chore: Normalize formatting of the JSON file

.github/workflows/ci-validation.yml, .gitignore, README.md, __init__.py, pyproject.toml, requirements.txt, test_harness.py
The current Python usage harness:
* is very, very, very slow;
* matches the patterns case-insensitively, which is not what the other languages' harnesses do, and is not how the patterns appear to be intended to be used;
* is missing the `matching_crawlers()` function that the Go harness provides.
This patch fixes all these issues. In some simple tests, the updated `is_crawler()` function is well over a _hundred times_ faster than the current version.
=> Improve Python usage harness

validate.go, validate_test.go
Most patterns are simple search strings (not special Regexp symbols). Some utilize ^ and $, which can be emulated in plaintext search by appending these characters to the text itself for matching as regular characters. Additionally, some patterns involve (xx|yy) or [xY] structures, which expand to several plaintexts. Rare patterns require real regexp matching.
I've applied these simplifications and modifications. They are detected automatically by function `analyzePattern` which returns the list of plain text patterns (all possible search strings) or the main liternal and a regexp in complex cases. The main literal is needed to know when to run the regexp.
Search strings are substituted with a random hex string of length 16 (to prevent spontaneous or intentional matching with anything), …
=> golang: speedup using TRIE

crawler-user-agents.json
There is no official information about the user-agent used by the bot, so I added URL of links previewer, using the bot.
I found the user-agent in the logs of HTTP server.
=> Add KeybaseBot

crawler-user-agents.json
Add a user agent used by [CookieHub](https://www.cookiehub.com/).
They don't disclose the user agents they use publicly but grepping the access logs with their crawler IPs, the user agent can be found. The IPs are available at:
https://docs.cookiehub.com/getting-started/faq
Discovering entries requires using that service.
=> Add CookieHubScan

crawler-user-agents.json
Copy pasted from: https://developers.cloudflare.com/fundamentals/reference/cloudflare-site-crawling/
Instead of the product page for each crawler, I would suggest pointing to the [Cloudflare site crawling page](https://developers.cloudflare.com/fundamentals/reference/cloudflare-site-crawling/). What do you think?
=> feat: Added additional Clouflare UAs

__init__.py, test_harness.py
pr for https://github.com/monperrus/crawler-user-agents/issues/381
=> feat: make case sensitivity optional

.github/workflows/tag-version.yml
The Go package manager works using git tags. Without tagging new releases dependabot will for example not automatically update this dependency.
Tested first here: https://github.com/erikdubbelboer/github-action-tag-version-test
Fixes: https://github.com/monperrus/crawler-user-agents/issues/399
=> Automatically tag new minor version release

.github/workflows/npm-publish.yml
It needs this to be able to tag a new release.
=> Give the npm Github Action write access

crawler-user-agents.json
Adds support for the Google-Ads-Conversions user agent to the crawler detection list.
- **Pattern**: `Google-Ads-Conversions`
- **Instance**: `Mozilla/5.0 AppleWebKit/537.36 Chrome/139.0.7258.127 Safari/537.36 Google-Ads-Conversions`
- **Official URL**: https://developers.google.com/google-ads/api/docs/conversions/upload-online
This user agent appears to be related to Google Ads Enhanced Conversions for Web feature. Based on Google's official documentation, this functionality involves sending user agent information when tracking conversion events for attribution purposes, though the specific user agent format is not explicitly documented.
The user agent has been observed in web traffic and follows the pattern of other Google advertising-related crawlers.
- [Google Ads API Documentation - …
=> Add Google-Ads-Conversions user agent
